# Schema for the configuration files of the Key module.

key.key.*:
  type: config_entity
  label: 'Key'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    key_type:
      type: string
      label: 'Key type'
    key_type_settings:
      type: key.type.[%parent.key_type]
      label: 'Key type settings'
    key_provider:
      type: string
      label: 'Key provider'
    key_provider_settings:
      type: key.provider.[%parent.key_provider]
      label: 'Key provider settings'
    key_value_input:
      type: string
      label: 'Key value input'
    key_value_input_settings:
      type: key.value_input.[%parent.key_value_input]
      label: 'Key value input settings'

key.type.*:
  type: mapping
  label: 'Key type settings'

key.provider.*:
  type: mapping
  label: 'Key provider settings'

key.provider.config:
  type: mapping
  label: 'Configuration'
  mapping:
    key_value:
      type: string
      label: 'Key Value'

key.provider.file:
  type: mapping
  label: 'File'
  mapping:
    file_location:
      type: string
      label: 'File Location'

key.value_input.*:
  type: mapping
  label: 'Key value input settings'
