key.key.*:
  type: config_entity
  label: 'Key'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    key_provider:
      type: string
      label: 'Key provider'
    key_provider_settings:
      type: key.key_provider.plugin.[id]
      label: 'Key provider settings'

key_provider:
  type: mapping
  label: 'Key provider settings'
  mapping:
    id:
      type: string
      label: 'ID'

key.key_provider.plugin.*:
  type: key_provider

key.key_provider.plugin.config:
  type: key_provider
  label: 'Configuration'
  mapping:
    key_value:
      type: string
      label: 'Key Value'

key.key_provider.plugin.file:
  type: key_provider
  label: 'File'
  mapping:
    file_location:
      type: string
      label: 'File Location'
